### PR TITLE
Added Portuguese pt-PT translation. #14

### PR DESCRIPTION
**Pull request by Joaolfelicio**

### CODE REVIEW

**Comment by alxnull** [comment]
Could you also translate the [html help file](https://github.com/Bluegrams/ScreenRuler/blob/master/ScreenRuler/Help/Help.en.html)? Thanks! Rest looks good.

**Comment by Joaolfelicio** [comment]
Ah yes, didn't noticed that file.
Will work on that after work.

**Comment by Joaolfelicio** [comment]
@alxnull Let me if everything looks good to you.
Thanks.

**Review by alxnull — APPROVED** [review]
Looks good! Thanks a lot for your help! 👍

**Comment by Joaolfelicio** [comment]
No problem mate, if you find anything else that I can help with, assign it to me! 🙂

**Pull request merged**
